/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  *
  * Project : STM32F4 CAN sniffer
  * Function:
  *   - Receive CAN frames on CAN1 (from Arduino + CAN shield)
  *   - Forward frames as ASCII text to PC via USART2 (FTDI)
  *
  * Toolchain:
  *   - STM32CubeMX for code generation (CAN, USART, GPIO)
  *   - Keil MDK-ARM for compilation and debugging
  *
  ******************************************************************************
  */

  #include "main.h"
  #include "can.h"
  #include "usart.h"
  #include "gpio.h"
  #include <stdio.h>
  #include <string.h>
  
  /* ------------------------------------------------------------------------- */
  /*                      Global variables                                     */
  
  
  /* CAN reception header and data buffer (max 8 bytes in classic CAN)        */
  CAN_RxHeaderTypeDef RxHeader;
  uint8_t RxData[8];
  
  /* Small buffer used to format text sent over UART                           */
  char uart_buffer[128];
  
  /* ------------------------------------------------------------------------- */
  /*                      Function prototypes                                  */
  /* ------------------------------------------------------------------------- */
  
  void SystemClock_Config(void);
  static void CAN_Filter_Config(void);
  void Start_CAN_Communication(void);
  volatile uint8_t can_msg_ready = 0; //nouveau

  
  /* ------------------------------------------------------------------------- */
  /*                      Retarget printf to USART2                            */
  /* ------------------------------------------------------------------------- */
  /**
    * @brief  Redirects printf() to USART2.
    *         This allows using printf() for debugging through the FTDI adapter.
    * @param  file: not used
    * @param  ptr : pointer to data
    * @param  len : length of data
    * @retval number of bytes transmitted
    */
  int _write(int file, char *ptr, int len)
  {
      HAL_UART_Transmit(&huart2, (uint8_t *)ptr, len, HAL_MAX_DELAY);
      return len;
  }
  
  /* ------------------------------------------------------------------------- */
  /*                                MAIN                                       */
  /* ------------------------------------------------------------------------- */
  
  int main(void)
  {
      /* 1) Initialize the HAL library:
            - Configure Flash prefetch, instruction cache, data cache
            - Configure SysTick timer (1 ms)
       */
      HAL_Init();
  
      /* 2) Configure the system clock:
            - HSI (16 MHz) used as PLL source
            - PLL ? SYSCLK = 84 MHz
            - APB1 = 42 MHz (CAN, USART2)
            - APB2 = 84 MHz
       */
      SystemClock_Config();
  
      /* 3) Initialize all configured peripherals (generated by CubeMX)       */
      MX_GPIO_Init();        /* GPIO (optional: LEDs, buttons, etc.)          */
      MX_CAN1_Init();
          MX_USART2_UART_Init();
      /* CAN1 (parameters from CubeMX)                 */
       /* USART2 (115200 8N1 for FTDI)                  */
  
      /* 4) Démarrer la communication CAN avec configuration complète:
            - Configurer les filtres (accepter tous les ID)
            - Démarrer le module CAN
            - Activer les interruptions FIFO0
       */
      Start_CAN_Communication();
  
      /* 5) Boucle principale :
            - Toute la réception CAN est gérée par le callback d'interruption
            - Ici, vous pouvez ajouter d'autres tâches de fond si nécessaire
            - La consommation CPU est très faible (mode attente)
       */
      while (1)
      {
          /* Boucle d'inactivité – faible consommation CPU, tout le travail */
          /* est effectué dans l'IRQ. Vous pouvez placer ici :                */
          /* - la gestion de la faible consommation d'énergie                 */
          /* - d'autres tâches de fond (watchdog, tests LED, etc.)           */
      }
  }
  
  /* ------------------------------------------------------------------------- */
  /*                    CAN filter configuration                               */
  /* ------------------------------------------------------------------------- */
  /**
    * @brief  Configurer les filtres CAN1 pour accepter tous les ID vers FIFO0.
    *         Configuration de type "sniffer" : pas de filtrage.
    *         
    *         Chaque trame CAN reçue sera traitée dans le callback de FIFO0.
    * @param  None
    * @retval None
    */
  static void CAN_Filter_Config(void)
  {
      CAN_FilterTypeDef sFilterConfig;
  
      /* Banque de filtre 0 (première banque disponible)                         */
      sFilterConfig.FilterBank = 0;
  
      /* Mode ID-MASK : compare l'ID reçu avec le masque spécifié               */
      sFilterConfig.FilterMode = CAN_FILTERMODE_IDMASK;
  
      /* Échelle 32 bits (ID + masque dans un seul registre 32 bits)            */
      sFilterConfig.FilterScale = CAN_FILTERSCALE_32BIT;
  
      /* Accepter tous les ID standards et étendus :                            */
      /* ID = 0x00000000, MASK = 0x00000000 (accepte tout)                      */
      sFilterConfig.FilterIdHigh      = 0x0000;   /* Bits 31-16 de l'ID         */
      sFilterConfig.FilterIdLow       = 0x0000;   /* Bits 15-0 de l'ID          */
      sFilterConfig.FilterMaskIdHigh  = 0x0000;   /* Bits 31-16 du masque       */
      sFilterConfig.FilterMaskIdLow   = 0x0000;   /* Bits 15-0 du masque        */
  
      /* Diriger les messages filtrés vers FIFO 0                               */
      sFilterConfig.FilterFIFOAssignment = CAN_FILTER_FIFO0;
  
      /* Activer ce filtre                                                      */
      sFilterConfig.FilterActivation = ENABLE;
  
      /* Pour une instance CAN unique sur STM32F4, c'est typiquement 14          */
      /* C'est le point où les filtres "esclaves" commencent                    */
      sFilterConfig.SlaveStartFilterBank = 14;
  
      if (HAL_CAN_ConfigFilter(&hcan1, &sFilterConfig) != HAL_OK)
      {
          Error_Handler();
      }
  }
  
  /* ------------------------------------------------------------------------- */
  /*                    CAN RX FIFO0 interrupt callback                        */
  /* ------------------------------------------------------------------------- */
  /**
    * @brief  Traiter une trame CAN reçue et l'envoyer via UART
    *         
    *         Cette fonction formate la trame CAN avec :
    *         - L'ID (11 bits pour standard, 29 bits pour étendu)
    *         - Le DLC (nombre d'octets de données)
    *         - Les octets de données en hexadécimal
    *         
    *         Format de sortie : "CAN Frame -> ID: 0xXXX, DLC: X, Data: XX XX XX ..."
    * @param  None
    * @retval None
    */
  void Process_CAN_Frame(void)
  {
      uint32_t id;
      uint8_t i;
      
      /* Déterminer le type de trame (Standard ou Étendue)                    */
      if (RxHeader.IDE == CAN_ID_STD)
      {
          id = RxHeader.StdId;  /* ID standard 11 bits                         */
      }
      else
      {
          id = RxHeader.ExtId;  /* ID étendu 29 bits                           */
      }
      
      /* Formater la chaîne de sortie                                          */
      int len = snprintf(uart_buffer, sizeof(uart_buffer), 
                        "CAN Frame -> ID: 0x%03lX, DLC: %lu, Data:", id, RxHeader.DLC);
      
      /* Ajouter les octets de données                                         */
      for (i = 0; i < RxHeader.DLC; i++)
      {
          len += snprintf(&uart_buffer[len], sizeof(uart_buffer) - len,
                         " %02X", RxData[i]);
      }
      
      /* Ajouter le saut de ligne                                              */
      len += snprintf(&uart_buffer[len], sizeof(uart_buffer) - len, "\r\n");
      
      /* Transmettre via UART avec timeout de 100 ms                           */
      HAL_UART_Transmit(&huart2, (uint8_t*)uart_buffer, len, 100);
  }
  
  /**
    * @brief USART2 Initialization Function
    * @param None
    * @retval None
    */
  
  
  /**
    * @brief  Callback d'interruption FIFO0 du module CAN
    *         
    *         Cette fonction est appelée automatiquement lorsqu'une trame CAN
    *         est reçue et placée dans FIFO0. Elle est invoquée par l'IRQ
    *         CAN1_RX0_IRQHandler via la couche HAL.
    *         
    *         Procédure :
    *         1. Vérifier que l'interruption vient bien de CAN1
    *         2. Récupérer la trame depuis FIFO0
    *         3. Appeler la fonction de traitement
    * @param  hcan: pointeur sur la structure de gestion du CAN
    * @retval None
    */
//Nouvelle version 
  void HAL_CAN_RxFifo0MsgPendingCallback(CAN_HandleTypeDef *hcan)
{
    if (hcan->Instance == CAN1)
    {
        if (HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &RxHeader, RxData) == HAL_OK)
        {
            can_msg_ready = 1;  
        }
    }
}

  /**
    * @brief  Démarrer la communication CAN et activer les interruptions
    *         
    *         Cette fonction effectue les étapes suivantes :
    *         1. Configurer les filtres CAN (pour le sniffing de tous les ID)
    *         2. Démarrer le module CAN (passer en mode Normal/Active)
    *         3. Activer l'interruption de FIFO0
    *         4. Afficher un message de confirmation sur UART
    *         
    *         Après cet appel, toutes les trames reçues seront traitées
    *         dans le callback HAL_CAN_RxFifo0MsgPendingCallback().
    * @param  None
    * @retval None
    */
  void Start_CAN_Communication(void)
  {
      /* Configurer les filtres CAN                                            */
      CAN_Filter_Config();
      
      /* Démarrer le module CAN                                                */
      if (HAL_CAN_Start(&hcan1) != HAL_OK)
      {
          Error_Handler();
      }
      
      /* Activer l'interruption de FIFO0 (message en attente)                  */
      if (HAL_CAN_ActivateNotification(&hcan1, CAN_IT_RX_FIFO0_MSG_PENDING) != HAL_OK)
      {
          Error_Handler();
      }
      
      /* Informer l'utilisateur que la communication est prête                 */
      printf("CAN Communication Started - Ready to receive frames...\r\n");
  }
  
  /* ------------------------------------------------------------------------- */
  /*                        System Clock Configuration                         */
  /* ------------------------------------------------------------------------- */
  /**
    * @brief  System Clock Configuration
    *         HSI (16 MHz) ? PLL ? SYSCLK = 84 MHz
    *         AHB  = 84 MHz
    *         APB1 = 42 MHz  (CAN, USART2)
    *         APB2 = 84 MHz
    */
  void SystemClock_Config(void)
  {
      RCC_OscInitTypeDef RCC_OscInitStruct = {0};
      RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
  
      /* Enable Power control clock                                             */
      __HAL_RCC_PWR_CLK_ENABLE();
      /* Voltage scaling                                                       */
      __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE2);
  
      /* Configure main internal oscillator (HSI) and PLL                       */
      RCC_OscInitStruct.OscillatorType        = RCC_OSCILLATORTYPE_HSI;
      RCC_OscInitStruct.HSIState              = RCC_HSI_ON;
      RCC_OscInitStruct.HSICalibrationValue   = RCC_HSICALIBRATION_DEFAULT;
      RCC_OscInitStruct.PLL.PLLState          = RCC_PLL_ON;
      RCC_OscInitStruct.PLL.PLLSource         = RCC_PLLSOURCE_HSI;
      RCC_OscInitStruct.PLL.PLLM              = 8;
      RCC_OscInitStruct.PLL.PLLN              = 84;
      RCC_OscInitStruct.PLL.PLLP              = RCC_PLLP_DIV2;   
      RCC_OscInitStruct.PLL.PLLQ              = 4;
  
      if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
      {
          Error_Handler();
      }
  
      /* Select PLL as system clock source and configure HCLK, PCLK1 and PCLK2 */
      RCC_ClkInitStruct.ClockType      = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK |
                                         RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
      RCC_ClkInitStruct.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
      RCC_ClkInitStruct.AHBCLKDivider  = RCC_SYSCLK_DIV1;      /* HCLK  = 84 MHz   */
      RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;        /* PCLK1 = 42 MHz   */
      RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;        /* PCLK2 = 84 MHz   */
  
      if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
      {
          Error_Handler();
      }
  }
  
  /* ------------------------------------------------------------------------- */
  /*                              Error Handler                                */
  /* ------------------------------------------------------------------------- */
  /**
    * @brief  Error handler: infinite loop with interrupts disabled.
    *         Can be improved by toggling an LED or sending debug info.
    */
  void Error_Handler(void)
  {
      __disable_irq();
      while (1)
      {
          /* Stay here to help debugging                                       */
      }
  }
  